# Generated by Django 5.1.6 on 2025-02-19 21:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DiscordServer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('discord_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='DiscordUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('discord_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='YTSong',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('youtube_id', models.CharField(max_length=128)),
                ('extension', models.CharField(max_length=16)),
                ('duration', models.IntegerField()),
                ('times_played', models.IntegerField(default=0)),
                ('times_favorited', models.IntegerField(default=0)),
                ('local_path', models.CharField(max_length=512)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='DiscordChannel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='concheddu_bot.discordserver')),
            ],
        ),
        migrations.AddField(
            model_name='discordserver',
            name='users',
            field=models.ManyToManyField(related_name='servers', to='concheddu_bot.discorduser'),
        ),
        migrations.CreateModel(
            name='PlaylistThrough',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField()),
                ('added_date', models.DateTimeField(auto_now_add=True)),
                ('playlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='concheddu_bot.playlist')),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='concheddu_bot.ytsong')),
            ],
        ),
        migrations.AddField(
            model_name='playlist',
            name='songs',
            field=models.ManyToManyField(related_name='playlists', through='concheddu_bot.PlaylistThrough', to='concheddu_bot.ytsong'),
        ),
        migrations.CreateModel(
            name='PlayEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='concheddu_bot.discorduser')),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='concheddu_bot.ytsong')),
            ],
        ),
        migrations.CreateModel(
            name='FavoriteSongThrough',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_date', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='concheddu_bot.discorduser')),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='concheddu_bot.ytsong')),
            ],
        ),
        migrations.AddField(
            model_name='discorduser',
            name='favorite_songs',
            field=models.ManyToManyField(related_name='users_favorite', through='concheddu_bot.FavoriteSongThrough', to='concheddu_bot.ytsong'),
        ),
        migrations.AddField(
            model_name='discorduser',
            name='played_songs',
            field=models.ManyToManyField(related_name='users', through='concheddu_bot.PlayEvent', to='concheddu_bot.ytsong'),
        ),
    ]
