# Generated by Django 5.1.6 on 2025-02-19 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concheddu_bot', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ytsong',
            name='duration',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='ytsong',
            name='extension',
            field=models.CharField(max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='ytsong',
            name='local_path',
            field=models.CharField(max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='ytsong',
            name='title',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
