# Generated by Django 5.1.6 on 2025-02-21 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("concheddu_bot", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="favoritesongthrough",
            old_name="added_date",
            new_name="date",
        ),
        migrations.RemoveField(
            model_name="discorduser",
            name="favorite_songs",
        ),
        migrations.RemoveField(
            model_name="discorduser",
            name="played_songs",
        ),
        migrations.RemoveField(
            model_name="ytsong",
            name="added_by",
        ),
    ]
