# Generated by Django 5.1.6 on 2025-02-22 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concheddu_bot', '0002_rename_added_date_favoritesongthrough_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discordserver',
            name='discord_id',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='discorduser',
            name='discord_id',
            field=models.BigIntegerField(),
        ),
    ]
