# Generated by Django 5.1.6 on 2025-03-05 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('concheddu_bot', '0003_alter_discordserver_discord_id_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FavoriteSongThrough',
        ),
    ]
