# Generated by Django 5.1.6 on 2025-03-08 21:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('concheddu_bot', '0004_delete_favoritesongthrough'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ytsong',
            old_name='title',
            new_name='original_title',
        ),
    ]
