# Generated by Django 5.1.6 on 2025-03-08 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concheddu_bot', '0005_rename_title_ytsong_original_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='ytsong',
            name='manual_title',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
