# Generated by Django 5.1.6 on 2025-03-09 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concheddu_bot', '0006_ytsong_manual_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='ytsong',
            name='times_answered',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ytsong',
            name='times_guessed',
            field=models.IntegerField(default=0),
        ),
    ]
