# Generated by Django 5.1.6 on 2025-03-09 01:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('concheddu_bot', '0007_ytsong_times_answered_ytsong_times_guessed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ytsong',
            name='local_path',
        ),
    ]
