# Generated by Django 5.1.6 on 2025-03-09 14:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concheddu_bot', '0008_remove_ytsong_local_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ytsong',
            name='youtube_id',
            field=models.CharField(max_length=128, unique=True),
        ),
        migrations.CreateModel(
            name='GuessSongEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('guessed_song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='concheddu_bot.ytsong')),
                ('real_song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='concheddu_bot.ytsong')),
                ('user', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='song_guesses', to='concheddu_bot.discorduser')),
            ],
        ),
    ]
