# Generated by Django 5.1.6 on 2025-03-10 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concheddu_bot', '0009_alter_ytsong_youtube_id_guesssongevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='guesssongevent',
            name='end',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='guesssongevent',
            name='num_choices',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='guesssongevent',
            name='start',
            field=models.IntegerField(null=True),
        ),
    ]
