# Generated by Django 5.1.6 on 2025-03-11 20:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concheddu_bot', '0010_guesssongevent_end_guesssongevent_num_choices_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='guesssongevent',
            name='num_plays',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='QuizSong',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_songs', models.IntegerField()),
                ('num_choices', models.IntegerField()),
                ('total_songs', models.IntegerField()),
                ('total_choices', models.IntegerField()),
                ('segment_mode', models.CharField(max_length=32)),
                ('segment_length', models.IntegerField()),
                ('audio_filter', models.CharField(max_length=512, null=True)),
                ('song_choice_ids', models.JSONField()),
                ('date_start', models.DateTimeField(auto_now_add=True)),
                ('date_end', models.DateTimeField(null=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='concheddu_bot.discorduser')),
                ('players', models.ManyToManyField(related_name='quizzes', to='concheddu_bot.discorduser')),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='concheddu_bot.discordserver')),
            ],
        ),
        migrations.AddField(
            model_name='guesssongevent',
            name='quiz',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='guesses', to='concheddu_bot.quizsong'),
        ),
    ]
