# Generated by Django 5.1.6 on 2025-03-12 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "concheddu_bot",
            "0011_guesssongevent_num_plays_playevent_audio_filter_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="guesssongevent",
            name="time_to_answer",
            field=models.IntegerField(null=True),
        ),
    ]
