# Generated by Django 5.1.6 on 2025-03-13 14:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("concheddu_bot", "0012_guesssongevent_time_to_answer"),
    ]

    operations = [
        migrations.CreateModel(
            name="CallCommandEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("command", models.CharField(max_length=512)),
                ("args", models.JSONField()),
                ("kwargs", models.JSONField()),
                ("error", models.TextField(null=True)),
                ("date", models.DateTimeField(auto_now_add=True)),
                (
                    "server",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="concheddu_bot.discordserver",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="concheddu_bot.discorduser",
                    ),
                ),
            ],
        ),
    ]
