# Generated by Django 5.1.6 on 2025-03-13 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concheddu_bot', '0013_callcommandevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizsong',
            name='multple_choice',
            field=models.BooleanField(default=True),
        ),
    ]
