# Generated by Django 5.1.6 on 2025-03-13 23:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concheddu_bot', '0014_quizsong_multple_choice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guesssongevent',
            name='guessed_song',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='concheddu_bot.ytsong'),
        ),
    ]
