# Generated by Django 5.1.6 on 2025-03-15 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concheddu_bot', '0015_alter_guesssongevent_guessed_song'),
    ]

    operations = [
        migrations.AddField(
            model_name='ytsong',
            name='thumbnail_urls',
            field=models.JSONField(null=True),
        ),
    ]
