# Generated by Django 5.1.6 on 2025-03-15 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concheddu_bot', '0016_ytsong_thumbnail_urls'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quizsong',
            old_name='multple_choice',
            new_name='multiple_choice',
        ),
        migrations.AddField(
            model_name='quizsong',
            name='show_thumbnail',
            field=models.BooleanField(default=False),
        ),
    ]
