# Generated by Django 5.1.6 on 2025-03-15 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concheddu_bot', '0017_rename_multple_choice_quizsong_multiple_choice_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizsong',
            name='thumbnail_blur',
            field=models.IntegerField(default=0),
        ),
    ]
