# Generated by Django 5.1.6 on 2025-03-16 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concheddu_bot', '0018_quizsong_thumbnail_blur'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ytsong',
            name='thumbnail_urls',
        ),
        migrations.AddField(
            model_name='guesssongevent',
            name='thumbnail',
            field=models.CharField(max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='ytsong',
            name='num_thumbnails',
            field=models.IntegerField(default=0),
        ),
    ]
