# Generated by Django 5.1.6 on 2025-03-16 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concheddu_bot', '0019_remove_ytsong_thumbnail_urls_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageObj',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=512, null=True)),
                ('local_path', models.CharField(max_length=512, null=True)),
                ('md5', models.CharField(max_length=32, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='ytsong',
            name='thumbnails',
            field=models.ManyToManyField(related_name='yt_songs', to='concheddu_bot.imageobj'),
        ),
    ]
