# Generated by Django 5.1.6 on 2025-03-16 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('concheddu_bot', '0020_imageobj_ytsong_thumbnails'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guesssongevent',
            name='thumbnail',
        ),
    ]
