# Generated by Django 5.1.6 on 2025-03-16 17:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concheddu_bot', '0021_remove_guesssongevent_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='guesssongevent',
            name='thumbnail',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='concheddu_bot.imageobj'),
        ),
    ]
