# Generated by Django 5.1.6 on 2025-03-16 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('concheddu_bot', '0022_guesssongevent_thumbnail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ytsong',
            name='num_thumbnails',
        ),
    ]
