# Generated by Django 5.1.6 on 2025-03-16 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concheddu_bot', '0023_remove_ytsong_num_thumbnails'),
    ]

    operations = [
        migrations.AddField(
            model_name='guesssongevent',
            name='blur',
            field=models.IntegerField(default=0),
        ),
    ]
