# Generated by Django 5.1.7 on 2025-05-25 19:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concheddu_bot', '0024_guesssongevent_blur'),
    ]

    operations = [
        migrations.AddField(
            model_name='playevent',
            name='quiz',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='plays', to='concheddu_bot.quizsong'),
        ),
    ]
