# Generated by Django 5.1.7 on 2025-05-29 17:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concheddu_bot', '0025_playevent_quiz'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnimeGenre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the anime genre', max_length=64, unique=True)),
                ('mal_id', models.IntegerField(blank=True, help_text='MyAnimeList ID of the genre', null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='AnimeStudio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the anime studio', max_length=512, unique=True)),
                ('mal_id', models.IntegerField(blank=True, help_text='MyAnimeList ID of the studio', null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='AnimeObj',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mal_id', models.IntegerField(unique=True)),
                ('title', models.CharField(help_text='Title of the anime', max_length=512)),
                ('title_english', models.CharField(blank=True, max_length=512, null=True)),
                ('title_japanese', models.CharField(blank=True, max_length=512, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('num_episodes', models.IntegerField(blank=True, help_text='Number of episodes in the anime', null=True)),
                ('release_date', models.DateField(blank=True, null=True)),
                ('aired_from', models.DateField(blank=True, help_text='Start date of airing', null=True)),
                ('aired_to', models.DateField(blank=True, help_text='End date of airing', null=True)),
                ('date', models.DateTimeField(auto_now_add=True, help_text='Creation date of the anime entry')),
                ('score', models.FloatField(blank=True, help_text='Average score from MyAnimeList', null=True)),
                ('scored_by', models.IntegerField(blank=True, help_text='Number of users who scored this anime on MyAnimeList', null=True)),
                ('rank', models.IntegerField(blank=True, help_text='Rank of the anime on MyAnimeList', null=True)),
                ('popularity', models.IntegerField(blank=True, help_text='Popularity score on MyAnimeList', null=True)),
                ('members', models.IntegerField(blank=True, help_text='Number of members on MyAnimeList', null=True)),
                ('favorites', models.IntegerField(blank=True, help_text='Number of favorites on MyAnimeList', null=True)),
                ('genres', models.ManyToManyField(blank=True, help_text='Genres of the anime', related_name='animes', to='concheddu_bot.animegenre')),
                ('places', models.ManyToManyField(blank=True, help_text='Images of places from the anime', related_name='anime_places', to='concheddu_bot.imageobj')),
                ('thumbnail', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='anime_thumbnails', to='concheddu_bot.imageobj')),
                ('studios', models.ManyToManyField(blank=True, help_text='Studios that produced the anime', related_name='animes', to='concheddu_bot.animestudio')),
            ],
        ),
        migrations.CreateModel(
            name='AnimeCharacter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512)),
                ('description', models.TextField(blank=True, null=True)),
                ('mal_id', models.IntegerField(blank=True, null=True, unique=True)),
                ('role', models.CharField(choices=[('main', 'Main Character'), ('supporting', 'Supporting Character')], default='main', help_text='Role of the character in the anime', max_length=64)),
                ('favorites', models.IntegerField(default=0, help_text='Number of favorites on MyAnimeList')),
                ('body_img', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='character_body', to='concheddu_bot.imageobj')),
                ('eyes_img', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='character_eyes', to='concheddu_bot.imageobj')),
                ('hair_img', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='character_hair', to='concheddu_bot.imageobj')),
                ('thumbnail', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='character_thumbnails', to='concheddu_bot.imageobj')),
                ('anime', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='characters', to='concheddu_bot.animeobj')),
            ],
        ),
        migrations.AddField(
            model_name='ytsong',
            name='anime',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='songs', to='concheddu_bot.animeobj'),
        ),
        migrations.CreateModel(
            name='VoiceActor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512)),
                ('mal_id', models.IntegerField(blank=True, null=True, unique=True)),
                ('thumbnail', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='voice_actor_thumbnails', to='concheddu_bot.imageobj')),
            ],
        ),
        migrations.CreateModel(
            name='VACthrough',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='throughs', to='concheddu_bot.animecharacter')),
                ('language', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='concheddu_bot.language')),
                ('voice_actor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='throughs', to='concheddu_bot.voiceactor')),
            ],
        ),
        migrations.AddField(
            model_name='animecharacter',
            name='voice_actors',
            field=models.ManyToManyField(blank=True, help_text='Voice actors who voiced this character in different languages', related_name='characters', through='concheddu_bot.VACthrough', to='concheddu_bot.voiceactor'),
        ),
    ]
