# Generated by Django 5.1.7 on 2025-05-29 23:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concheddu_bot', '0026_animegenre_animestudio_language_animeobj_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizHighLow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_type', models.CharField(choices=[('anime', 'Anime'), ('anime_character', 'Anime Character')], max_length=32)),
                ('object_param', models.CharField(blank=True, max_length=64, null=True)),
                ('num_objects', models.IntegerField(default=0)),
                ('object_choice_ids', models.JSONField()),
                ('date_start', models.DateTimeField(auto_now_add=True)),
                ('date_end', models.DateTimeField(null=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_highlow', to='concheddu_bot.discorduser')),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='concheddu_bot.discordserver')),
            ],
        ),
        migrations.CreateModel(
            name='GuessHighLowEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item1_id', models.IntegerField(null=True)),
                ('item2_id', models.IntegerField(null=True)),
                ('direction', models.IntegerField(choices=[(1, 'Item 2 is higher'), (-1, 'Item 2 is lower')])),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='highlow_guesses', to='concheddu_bot.discorduser')),
                ('quiz', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='guesses', to='concheddu_bot.quizhighlow')),
            ],
        ),
    ]
