# Generated by Django 5.1.7 on 2025-05-30 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concheddu_bot', '0027_quizhighlow_guesshighlowevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizhighlow',
            name='max_top',
            field=models.IntegerField(default=0),
        ),
    ]
