# Generated by Django 5.1.7 on 2025-05-30 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concheddu_bot', '0028_quizhighlow_max_top'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='animeobj',
            name='release_date',
        ),
        migrations.AddField(
            model_name='animeobj',
            name='source',
            field=models.CharField(choices=[('original', 'Original'), ('manga', 'Manga'), ('light_novel', 'Light Novel'), ('visual_novel', 'Visual Novel'), ('video_game', 'Video Game'), ('other', 'Other')], default='original', help_text='Source material of the anime', max_length=64),
        ),
        migrations.AddField(
            model_name='animeobj',
            name='type',
            field=models.CharField(choices=[('tv', 'TV'), ('movie', 'Movie'), ('ova', 'OVA'), ('ona', 'ONA'), ('special', 'Special'), ('music', 'Music')], default='tv', help_text='Type of the anime', max_length=64),
        ),
    ]
