# Generated by Django 5.1.7 on 2025-05-31 01:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concheddu_bot', '0029_remove_animeobj_release_date_animeobj_source_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizAnimeCharacter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_objects', models.IntegerField(default=0)),
                ('max_top', models.IntegerField(default=0)),
                ('object_choice_ids', models.JSONField()),
                ('date_start', models.DateTimeField(auto_now_add=True)),
                ('date_end', models.DateTimeField(null=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='concheddu_bot.discorduser')),
                ('players', models.ManyToManyField(related_name='quiz_anime_characters', to='concheddu_bot.discorduser')),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='concheddu_bot.discordserver')),
            ],
        ),
        migrations.CreateModel(
            name='GuessAnimeCharacterEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('guessed_anime', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='concheddu_bot.animeobj')),
                ('guessed_character', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='concheddu_bot.animecharacter')),
                ('real_character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='concheddu_bot.animecharacter')),
                ('user', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='character_guesses', to='concheddu_bot.discorduser')),
                ('quiz', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='guesses', to='concheddu_bot.quizanimecharacter')),
            ],
        ),
    ]
