# Generated by Django 5.1.7 on 2025-05-31 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concheddu_bot', '0030_quizanimecharacter_guessanimecharacterevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizanimecharacter',
            name='max_choices',
            field=models.IntegerField(default=0),
        ),
    ]
