# Generated by Django 5.1.7 on 2025-05-31 15:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concheddu_bot', '0031_quizanimecharacter_max_choices'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='animecharacter',
            name='anime',
        ),
        migrations.CreateModel(
            name='AnimeCharacterThrough',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anime', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='concheddu_bot.animeobj')),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='concheddu_bot.animecharacter')),
                ('role', models.ForeignKey(blank=True, help_text='Role of the character in the anime', null=True, on_delete=django.db.models.deletion.SET_NULL, to='concheddu_bot.role')),
            ],
            options={
                'unique_together': {('anime', 'character')},
            },
        ),
    ]
