# Generated by Django 5.1.7 on 2025-05-31 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concheddu_bot', '0032_role_remove_animecharacter_anime_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='animecharacter',
            name='role',
        ),
        migrations.AddField(
            model_name='animecharacter',
            name='animes',
            field=models.ManyToManyField(help_text='Animes this character appears in', related_name='characters', through='concheddu_bot.AnimeCharacterThrough', to='concheddu_bot.animeobj'),
        ),
    ]
