# Generated by Django 5.1.7 on 2025-05-31 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concheddu_bot', '0033_remove_animecharacter_role_animecharacter_animes'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizanimecharacter',
            name='max_favorites',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='quizanimecharacter',
            name='min_favorites',
            field=models.IntegerField(default=-1),
        ),
    ]
