# Generated by Django 5.1.7 on 2025-06-09 14:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concheddu_bot', '0034_quizanimecharacter_max_favorites_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnimeCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the anime collection', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Creation date of the collection')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Last update date of the collection')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anime_collections_owned', to='concheddu_bot.discorduser')),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anime_collections', to='concheddu_bot.discordserver')),
            ],
        ),
        migrations.CreateModel(
            name='AnimeCollectionThrough',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(blank=True, help_text='Date started watching the anime in this collection', null=True)),
                ('end_date', models.DateField(blank=True, help_text='Date finished watching the anime in this collection', null=True)),
                ('score', models.IntegerField(blank=True, help_text='Score given to the anime in this collection', null=True)),
                ('cdate', models.DateTimeField(auto_now=True, help_text='Date when the collection was last updated')),
                ('anime', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collections', to='concheddu_bot.animeobj')),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='animes', to='concheddu_bot.animecollection')),
            ],
            options={
                'unique_together': {('anime', 'collection')},
            },
        ),
    ]
