# Generated by Django 5.1.7 on 2025-06-09 15:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concheddu_bot', '0035_animecollection_animecollectionthrough'),
    ]

    operations = [
        migrations.AddField(
            model_name='animecollection',
            name='animes',
            field=models.ManyToManyField(help_text='Animes in this collection', related_name='collections', through='concheddu_bot.AnimeCollectionThrough', to='concheddu_bot.animeobj'),
        ),
        migrations.AlterField(
            model_name='animecollectionthrough',
            name='anime',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='concheddu_bot.animeobj'),
        ),
        migrations.AlterField(
            model_name='animecollectionthrough',
            name='collection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='concheddu_bot.animecollection'),
        ),
    ]
