# Generated by Django 5.1.7 on 2025-06-09 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concheddu_bot', '0036_animecollection_animes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizanimecharacter',
            name='collections',
            field=models.ManyToManyField(blank=True, help_text='Collections to filter the characters from', related_name='quiz_anime_characters', to='concheddu_bot.animecollection'),
        ),
        migrations.AddField(
            model_name='quizanimecharacter',
            name='max_anime_choices',
            field=models.IntegerField(default=0),
        ),
    ]
