# Generated by Django 5.1.7 on 2025-06-09 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concheddu_bot', '0037_quizanimecharacter_collections_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quizhighlow',
            old_name='player',
            new_name='creator',
        ),
        migrations.AddField(
            model_name='quizhighlow',
            name='collections',
            field=models.ManyToManyField(blank=True, related_name='quiz_highlow_collections', to='concheddu_bot.animecollection'),
        ),
        migrations.AddField(
            model_name='quizhighlow',
            name='max_failures',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='quizhighlow',
            name='players',
            field=models.ManyToManyField(related_name='quiz_highlow_players', to='concheddu_bot.discorduser'),
        ),
    ]
