# Generated by Django 5.1.7 on 2025-06-19 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concheddu_bot', '0038_rename_player_quizhighlow_creator_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizanimecharacter',
            name='image_type',
            field=models.CharField(default='thumbnail', help_text='Type of image to use for the characters (thumbnail, eyes, etc.)', max_length=64),
        ),
    ]
